[tox]
skipsdist = True
envlist =
  py311-django{42,52}
  py313-django{42,52,60}
skip_missing_interpreters = true

[testenv]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/django_grpc
    DJANGO_SETTINGS_MODULE = tests.settings
    PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION = python

commands =
    pytest -vv tests/ --junitxml=test-report.xml

allowlist_externals =
    pytest
    poetry


deps =
    .[qa]
    django42: Django>=4.2,<5.0
    django52: Django>=5.2,<6.0
    django60: Django>=6.0,<7.0
